# Generated by Django 4.2.10 on 2024-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification_comment_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
