# Generated by Django 5.0.1 on 2024-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_followers_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
