# Generated by Django 5.0.1 on 2024-02-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_following_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
