# Generated by Django 4.2.10 on 2024-02-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
