# Generated by Django 4.2.10 on 2024-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_onlineuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
