# Generated by Django 4.2.10 on 2024-02-27 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_following_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
