# Generated by Django 5.0.1 on 2024-01-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofile_cover_photo_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
